### ISSUE TITLE
Env file should be simple key value pairs

### ISSUE THREAD

**Issue by Nepomuceno** [IQEngine/IQEngine#35]
It is a common patter to use simple key values for envitonment parameters instead of  complex objects or json.

**Comment by 777arc** [comment]
How would that work for a list of storage accounts?  The only time I've come across lists of stuff in env vars is like PATH which has colons separating each entry but that feels weird for a list of sets of info

**Comment by 777arc** [comment]
or is the point here to not specify such information in the env var but instead somewhere else?  the env var is convenient when deploying IQEngine through an azure app service because you just set the value in the app service settings, i.e. the string from the .env file can be copy/pasted into the app service setting.

**Comment by Nepomuceno** [comment]
The idea it is that configuration data could live in a config object that could be stored in a databased or file. environment settings are normally used for smaller starter things.

**Comment by 777arc** [comment]
Ok, we'll start with a file (I assume json file?), because currently IQEngine is database-less, which isn't always going to be the case, but I want to make sure once we add the database its done with as much planning as possible, and for a specific reason (not just to hold these basic settings).
